### ISSUE TITLE
bot responds with no data

### ISSUE THREAD

**Issue by azrethos** [ErlendEllingsen/wowclassicpricebot-website#1]
whitemane alliance

![tempsnip](https://user-images.githubusercontent.com/46342168/74761590-240e1800-5231-11ea-8816-c6ee55197e93.png)

config'd with  `wowpricebot-serversetup whitemane-alliance item-prices`

**Comment by ErlendEllingsen** [comment]
![image](https://user-images.githubusercontent.com/977988/74761781-efc04900-527c-11ea-9593-ba353edd34e4.png)

I am not able to reproduce this bug. Mind adding me to your Discord so I can debug? Erlend#7036 on DC.

**Comment by azrethos** [comment]
added

**Comment by ErlendEllingsen** [comment]
**Solution A:** The user had disabled the following setting "link preview". This must be **enabled** for wowpricebot's messages to display correctly.

![image](https://user-images.githubusercontent.com/977988/74774312-bcd57f80-5293-11ea-8e53-0aaf8f88e0fa.png)

See more:
https://old.reddit.com/r/discordapp/comments/5ofhol/cannot_see_bot_messages/

**Comment by ErlendEllingsen** [comment]
**Solution B:** Ensure that the bot has PERMISSION in the channel to post link previews and embedded messages. 

![image](https://user-images.githubusercontent.com/977988/74830525-a4a54500-5313-11ea-8f03-49f6975fe386.png)
