### ISSUE TITLE
[feature request] Notification when trigger is met

### ISSUE THREAD

**Issue by padmanek** [ErlendEllingsen/wowclassicpricebot-website#13]
For example:
notify [item] [price] -> notifies with @mention when [item] minimum buyout price is<= [price]
Could also be
notify [item][quantity] -> similar as above but will notify when available quanity of [item] on AH is >=[quantity]
notify item [price][quantity] -> a combination of both

Example usage:
notify major mana 3.5g ->notifies when price hits 3.5g
notify major mana 20 -> notifies when theres >= 20 available on the AH
notify major mana 3.5g 10 -> notifies when there's >= 10 major mana potions for 3.5g or less.

**Comment by ErlendEllingsen** [comment]
This is now done and live! 

The following features can be used:
`alarm-add <item-name> <lt|gt> <price> <quantity>`
e.g.
`alarm-add mooncloth gt 17g 1`

and:
`alarm-list`
`alarm-remove <id>`
