### ISSUE TITLE
language issue

### ISSUE THREAD

**Issue by loronn** [ErlendEllingsen/wowclassicpricebot-website#18]
noticed a bug where "price Encrypted Twilight Text" is working but the german translation "price Verschlüsselter Text der Twilight" is not.

Issue: "Artikel ist nicht auf AH verfügbar Dwarven Leather Pants (61)
Dies könnte auch bedeuten, dass die eingestellte Realm-Fraktion ungültig ist."

**Comment by loronn** [comment]
server is everlook-alliance

**Comment by loronn** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/64896098/81161001-2871e380-8f8b-11ea-9875-7dd17f7d69cf.png)

**Comment by ErlendEllingsen** [comment]
Thank you. I have updated the item in german, its live now:

![image](https://user-images.githubusercontent.com/977988/81164813-3e82a280-8f91-11ea-9c8d-f0f0d9b984c4.png)
