### ISSUE TITLE
"craftprice" fails if craftable item is NOT on AH

### ISSUE THREAD

**Issue by fossett** [ErlendEllingsen/wowclassicpricebot-website#2]
It looks like when running craftprice for an item that isn't currently on the AH, the bot won't list the mats.

<img width="422" alt="test" src="https://user-images.githubusercontent.com/2635310/74780810-f98a8200-5265-11ea-9d8d-6c4ff7112059.png">

I confirmed the item is not listed on the AH, however it seems like the bot should list crafting mats if they are available, regardless if the item itself is not.

**Comment by ErlendEllingsen** [comment]
This has now been fixed. Craftable BoP items are now supported.

![image](https://user-images.githubusercontent.com/977988/75101211-1eba2000-55d9-11ea-9406-dfa876e854c0.png)
