### ISSUE TITLE
craftprice uses AH prices for items easily obtained from vendors

### ISSUE THREAD

**Issue by jasonlotito** [ErlendEllingsen/wowclassicpricebot-website#3]
For example, at the moment

```
craftprice greater shadow protection potion

Material: Shadow Oil x 1
6.688 g (AH: Y Q>=1)
Material: Dreamfoil x 1
0.820 g (AH: Y Q>=1)
Material: Crystal Vial x 1
1.927 g (AH: N)
Total crafting price
9.43 g
```

Obviously a Crystal Vial is not 1.927g.  While I realize how it got this price, certain items should be set at vendor prices regardless of what the AH says.

**Comment by jasonlotito** [comment]
Apparently this is all from Nexus Hub, which has a ticket open for this: https://github.com/nexus-devs/NexusHub/issues/336

**Comment by ErlendEllingsen** [comment]
I will fix this, im guessing it will take a day or two.

**Comment by ErlendEllingsen** [comment]
![image](https://user-images.githubusercontent.com/977988/74879897-6a1ac700-536a-11ea-8f26-87f3f4da4776.png)

This feature has been added and is now live.
