### ISSUE TITLE
Other languages (item search)

### ISSUE THREAD

**Issue by nudl3r** [ErlendEllingsen/wowclassicpricebot-website#5]
Is it possible to include other translations into the search engine?

We are using the bot in our guild discord and some of us are using the german wow client and don't know the english item names.

I know this is not that important, but I thought I could request it at least.

**Comment by ErlendEllingsen** [comment]
The only problem I'm facing with this is that I only have a list of english item names for WoW Classic.. I'm not really sure how to get a list in German (or other languages)

**Comment by nudl3r** [comment]
Thanks for your quick reply! Maybe I can help with this. 
Do you have a list with item IDs + names and could you send it to me?

**Comment by ErlendEllingsen** [comment]
Nevermind! I have solved the problem. Multi-language support will soon come.
Will support:

- German
- Russian
- French 
- Chinese

**Comment by nudl3r** [comment]
That's great, thank you so much!

**Comment by ErlendEllingsen** [comment]
This feature is now added and is live. Use `wowpricebot-language de` to switch to German
