### ISSUE TITLE
[Feature Request] Add current price to craftprice output

### ISSUE THREAD

**Issue by ninthwalker** [ErlendEllingsen/wowclassicpricebot-website#6]
When using craftprice I always want to compare to the current price.
Would be nice if craftprice included the current price as well.
Would limit users having to type multiple commands and probably API requests as well

**Comment by ErlendEllingsen** [comment]
Not a bad idea. Will implement this.

**Comment by ErlendEllingsen** [comment]
This is now implemented and live.
![image](https://user-images.githubusercontent.com/977988/75101375-e36d2080-55db-11ea-9502-1f4e705ed970.png)
